### ISSUE TITLE
Istanbul Mocha Integration

### ISSUE THREAD

**Issue by MerryOscar** [Milksnatcher/DefaultTests#1]
Hi,

Thanks for these examples.

Do you know if it's possible to implement Istanbul test coverage with the Jovo test framework?

https://istanbul.js.org/docs/tutorials/mocha/

I've tried adding it but I think maybe because the server is running separately it's not registering that the code in the handlers is being executed.

Any ideas on how to set this up properly?

**Comment by rubenaeg** [comment]
There is a good chance that it doesn't work, because the server runs in another instance. However you have the possibility to start the server in a before() statement, so it runs automatically with "npm test", although this will be kind of messy, because per default you get the output from your Jovo app and from your tests mashed together.

**Comment by MerryOscar** [comment]
Thanks - how would you start the server within the before() statement?

**Comment by MerryOscar** [comment]
I managed to get the coverage data by adding the Istanbul `nyc` prefix to the `jovo run` command, and then just running the tests normally.

In one terminal window: `nyc jovo run`

In another window: `mocha test`

The coverage information is then available when you terminate the Jovo server.
