### ISSUE TITLE
Specify Entity Resolution Result

### ISSUE THREAD

**Issue by MerryOscar** [Milksnatcher/DefaultTests#2]
In the examples you can send an intent via:

```javascript
send(rb.intent('CaptureWorldCountry', { country: 'germany' });
```

Is there a way to specify / mock the entity resolution result from Alexa, so that you can write tests that cover the cases where we have an exact match (`ER_SUCCESS_MATCH`) or a no match (`ER_SUCCESS_NO_MATCH `)?

Some thing like:

ER_SUCCESS_MATCH:
```javascript
send(rb.intent('CaptureWorldCountry', { country: { value: 'germany', id: 'germany' } } );
```

ER_SUCCESS_NO_MATCH:
 ```javascript
send(rb.intent('CaptureWorldCountry', { country: { value: 'germani', id: '' } } );
```

This would be really helpful in testing the different behaviour depending on an exact match or not.

Thanks!

**Comment by rubenaeg** [comment]
As of for now I don't think it's possible to add this information to the RequestBuilder due to the lack of implementation. But you could try to build your intent request as you would normally and then manually add the resolutions attribute.

So for example, create your intent request like
```javascript
let intentRequest = rb.intent('CaptureWorldCountry', { country: { value: 'germany', id: 'germany' } } );
```
This will store the intent request in your variable as a json object, which you can then manipulate the way you'd like to, so for this example it would be 
```javascript
intentRequest.request.intent.slots.resolutions = {
                   //your entity resolution object here 
}
```
Feel free to test around with this.
